Chm\Bundle\DocumentBundle\Entity\Delivery:
    type: entity
    table: delivery
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        sourceIp:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: source_ip
        userAgent:
            type: text
            nullable: true
            column: user_agent
        success:
            type: boolean
            nullable: true
        failureMessage:
            type: text
            nullable: true
            column: failure_message
        createdAt:
            type: datetime
            nullable: false
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        document:
            targetEntity: Document
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                document_id:
                    referencedColumnName: id
            orphanRemoval: false
        createdBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                blameable:
                    on: create
        updatedBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                blameable:
                    on: create
    lifecycleCallbacks: {  }
