Chm\Bundle\DocumentBundle\Entity\Document:
    type: entity
    table: document
    repositoryClass: Chm\Bundle\DocumentBundle\Entity\DocumentRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        slug:
            type: string
            length: 255
            fixed: false
            nullable: false
            unique: true
            column: slug
            gedmo:
                slug:
                    separator: _
                    style: camel
                    fields:
                        - id
                        - niceName
                        - extension
        niceName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: nice_name
        extension:
            type: string
            length: 20
            nullable: false
        fileName:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: file_name
        filePath:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: file_path
        mimeType:
            type: string
            length: 100
            fixed: false
            nullable: true
        notifySuccess:
            type: boolean
            nullable: true
            column: notify_success
        notifyFailure:
            type: boolean
            nullable: true
            column: notify_failure
        createdAt:
            type: datetime
            nullable: false
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        createdBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                blameable:
                    on: create
        updatedBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                blameable:
                    on: update
    oneToMany:
        ipRestrictions:
            targetEntity: IpRestriction
            mappedBy: document
            cascade: [ persist, remove ]
        secretRestrictions:
            targetEntity: SecretRestriction
            mappedBy: document
            cascade: [ persist, remove ]
        downloadCountRestrictions:
            targetEntity: DownloadCountRestriction
            mappedBy: document
            cascade: [ persist, remove ]
        userRestrictions:
            targetEntity: UserRestriction
            mappedBy: document
            cascade: [ persist, remove ]
        dateRestrictions:
            targetEntity: DateRestriction
            mappedBy: document
            cascade: [ persist, remove ]
        deliveries:
            targetEntity: Delivery
            mappedBy: document
            cascade: [ persist, remove ]
    lifecycleCallbacks: {  }
