Chm\Bundle\DocumentBundle\Entity\Document:
    type: entity
    table: document
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        slug:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: slug
        niceName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: nice_name
        filetype:
            type: string
            length: 10
            fixed: false
            nullable: true
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        validTo:
            type: datetime
            nullable: true
            column: valid_to
        notifySuccess:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: notify_success
        notifyFailure:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: notify_failure
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
