Chm\Bundle\DocumentBundle\Entity\Document:
    type: entity
    table: document
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        slug:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: slug
        niceName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: nice_name
        file:
            type: file
            nullable: false
            column: filepath
        filetype:
            type: string
            length: 10
            fixed: false
            nullable: true
        validTo:
            type: datetime
            nullable: true
            column: valid_to
        notifySuccess:
            type: boolean
            nullable: true
            column: notify_success
        notifyFailure:
            type: boolean
            nullable: true
            column: notify_failure
        createdAt:
            type: datetime
            nullable: false
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        createdBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                blameable:
                    on: create
        updatedBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
            gedmo:
                blameable:
                    on: create
    oneToMany:
        ip_restrictions:
            targetEntity: IpRestriction
            mappedBy: document
            cascade: [ persist ]
        secret_restrictions:
            targetEntity: SecretRestriction
            mappedBy: document
        download_count_restrictions:
            targetEntity: DownloadCountRestriction
            mappedBy: document
        user_restrictions:
            targetEntity: UserRestriction
            mappedBy: document
    lifecycleCallbacks: {  }
