Chm\Bundle\DocumentBundle\Entity\SecretRestriction:
    type: entity
    table: secret_restriction
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        secret:
            type: string
            length: 255
            fixed: false
            nullable: true
        comment:
            type: text
            nullable: true
    manyToOne:
        document:
            targetEntity: Document
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                document_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
