Chm\Bundle\DocumentBundle\Entity\SecretRestriction:
    type: entity
    table: secret_restriction
    fields:
        id:
            id: true
            type: string
            length: 45
            fixed: false
            nullable: false
            generator:
                strategy: IDENTITY
        secret:
            type: string
            length: 255
            fixed: false
            nullable: true
        comment:
            type: text
            nullable: true
    manyToOne:
        document:
            targetEntity: Document
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                document_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
