chm_document_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ChmDocumentBundle:Default:index }

download:
    pattern: /download/{document_slug}
    defaults: { _controller: ChmDocumentBundle:DownloadDocument:download }
