chm_document_download:
    pattern: /download/{slug}
    defaults: { _controller: ChmDocumentBundle:DownloadDocument:download }

chm_document_list:
    pattern: /admin/
    defaults: { _controller: ChmDocumentBundle:DocumentUpload:list }
chm_document_create:
    pattern: /admin/create
    defaults: { _controller: ChmDocumentBundle:DocumentUpload:edit, id: 0 }
chm_document_edit:
    pattern: /admin/edit/{id}
    defaults: { _controller: ChmDocumentBundle:DocumentUpload:edit }
chm_document_save:
    pattern: /admin/save
    defaults: { _controller: ChmDocumentBundle:DocumentUpload:save }
chm_document_delete:
    pattern: /admin/delete/{id}
    defaults: { _controller: ChmDocumentBundle:DocumentUpload:delete }
